### ISSUE TITLE
Argument 1 passed to Cfscrape\Cfscrape::isCloudflareCaptchaChallenge() must be an instance of Psr\Http\Message\ResponseInterface, null given, called in C:\Users\gerardo.palmiotto\PhpStormProjects\laravel-zero-ffmpeg\vendor\cfscrape\cfscrape\src\Cfscrape.php on li ne 158

### ISSUE THREAD

**Issue by tiaxter** [ScoLib/cfscrape#1]
My code:
![image](https://user-images.githubusercontent.com/33230281/87227001-0e43ef80-c398-11ea-8291-31fb1effeac3.png)

The error:
![image](https://user-images.githubusercontent.com/33230281/87226998-02f0c400-c398-11ea-9504-9499957d1d0b.png)

**Comment by grunkle-stan** [comment]
Got the same :(
How did you fix it?

**Comment by tiaxter** [comment]
> Got the same :(
> How did you fix it?

I don't remember very well, but have you tried to update GuzzleHttp to the last version? If I remember correctly it solved my problems

**Comment by grunkle-stan** [comment]
Thank for the quick answer! My problem was solved too, but I can't explain how is )) Maybe it's gone after php-curl module installation.
